hypertrace/service-framework

platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java

Otherwise, integration tests were having NPE.

Making the 'app' label optional for services.

---

platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
platform-metrics/src/test/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistryTest.java

fix ConcurrentModificationException while PlatformMetricsRegistry stop

fix ConcurrentModificationException while PlatformMetricsRegistry stop

---

platform-metrics/build.gradle.kts
platform-service-framework/build.gradle.kts

update to resolve https://snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-1080611

chore: update jetty due to vulnerability

---

platform-metrics/build.gradle.kts
platform-service-framework/build.gradle.kts

Update vulnerabilities
UTs
- [N/A] I have added tests that prove my fix is effective or that my feature works

chore: update vulnerabilities

---

platform-service-framework/build.gradle.kts

fix: update log4j

---

platform-service-framework/build.gradle.kts

chore: update log4j version to 2.17.0

---

platform-metrics/build.gradle.kts
platform-service-framework/build.gradle.kts

Update jetty version due to https://security.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-2945452

chore: update jetty to fix vuln

---

platform-grpc-service-framework/build.gradle.kts

See https://github.com/hypertrace/java-grpc-utils/pull/32 for context, depends on that PR

refactor: use new utils that better constrain netty

---

platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/PlatformServiceLauncher.java

Make calling istio pilot quit endpoint configurable

Silently fail the istio pilot quit call 

---

platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/HttpHandlerDefinition.java
platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/jetty/JettyHttpServerBuilder.java

Allow more flexibility when configuring servlets by exposing init params

refactor: add init param config

---

platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServerDefinition.java
platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java

Expose a way of adding server-level interceptors

refactor: expose server interceptors

---

platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/jetty/JettyHttpServerBuilder.java

Removes metadata about server version and servlet selected on response.

fix: hide http server information

---

platform-http-service-framework/build.gradle.kts
platform-metrics/build.gradle.kts
platform-service-framework/build.gradle.kts

Couple minor vulnerabilities in jetty.

chore: update jetty

---

owasp-suppressions.xml
platform-grpc-service-framework/build.gradle.kts
platform-http-service-framework/build.gradle.kts

refactor: update grpc to 1.60 and remove old suppressions

---

owasp-suppressions.xml

chore: update suppression

---

gradle/libs.versions.toml

Update doc store version to latest

fix: update doc store version

---

platform-grpc-service-framework/build.gradle.kts
platform-http-service-framework/build.gradle.kts

Upgrade GRPC framework to get netty update

chore: update grpc framework to update netty

---

owasp-suppressions.xml

fix: update suppression expiration

---

gradle/libs.versions.toml

chore: update document store version

---

gradle/libs.versions.toml

chore: update document-store version

---

platform-http-service-framework/build.gradle.kts
platform-metrics/build.gradle.kts
platform-service-framework/build.gradle.kts

A few suppressions for FPs or no fix available added in https://github.com/hypertrace/github-actions/pull/61

fix: update jetty

---

platform-grpc-service-framework/build.gradle.kts
platform-http-service-framework/build.gradle.kts

Pull in https://github.com/hypertrace/java-grpc-utils/pull/64 (once merged)

chore: update grpc, netty

---

owasp-suppressions.xml

Move micrometer client vuln suppression to global

---

gradle/libs.versions.toml

chore: upgrade document-store version
