- integrationtest-service-framework/src/main/java/org/hypertrace/core/serviceframework/IntegrationTestServiceLauncher.java
- integrationtest-service-framework/src/main/java/org/hypertrace/core/serviceframework/config/IntegrationTestConfigClient.java
- platform-metrics/build.gradle.kts
- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/MetricsServlet.java
- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
- platform-service-framework/build.gradle.kts
- platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/PlatformService.java
- platform-service-framework/src/test/java/org/hypertrace/core/serviceframework/PlatformServiceTest.java
This would let the services to leverage tags support for metrics. For example, we could track request latencies labelled by the tenant id.
**Default tags:**
`app:service-name` will be the default tag that's added for every metric but each service can add more default tags, like the cloud region, az, data center location, etc with the property `metrics.defaultTags`. 
Example: `metrics.defaultTags = az,us-west-1a,region,us-west`
**No more metric prefix:**
Since each metric has `app` label/tag now, metric name itself doesn't need to have the prefix, which is the case right now. This makes it super easy to easily share the Grafana dashboards across the services and also makes the metric names much shorter.
**/metrics for all metrics**
`/metrics` endpoint on the admin server exposes all the …
> Adding support for MicroMeter metrics in the service framework.

- integrationtest-service-framework/build.gradle.kts
- platform-metrics/build.gradle.kts
- platform-service-framework/build.gradle.kts
Update most framework dependencies, including jetty which is flagging https://snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-1047304 across most projects
Build and tested the framework project - also updated graphql locally to use the new framework artifact and verified basic functionality.
> chore: bump dependencies

- platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/PlatformService.java
As part of the issue -https://github.com/hypertrace/hypertrace/issues/137, where we identified that some sensitive information is logged (password for postgres), we are going with option (a) listed in the issue. As discussed in the issue, we will let consumers decide on logging in with actionable information.
> chore: discarding printing of entire application config for security

- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
Reference: https://stackoverflow.com/questions/50821924/micrometer-prometheus-gauge-displays-nan
> Fix issue where guage metrics arent reported at times

- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
- platform-metrics/src/test/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistryTest.java
Adding support to register distribution summary in PlatformMetricsRegistry
https://micrometer.io/docs/concepts#_distribution_summaries
> ENG-9598 Adding distribution summary support

- platform-metrics/build.gradle.kts
- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
- platform-metrics/src/test/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistryTest.java
Implemented GuavaCache Metric Support (registerCache) which registers cache metrics with the Metric Registry. 
Test includes testCache, which tests the cache values, cacheStats and if monitoring cache is changing when another cache is registered.
> ENG 5066: GuavaCacheMetric Support

- platform-metrics/build.gradle.kts
- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
- platform-metrics/src/test/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistryTest.java
ENG-5066: GuavaCacheMetric Support. 
Ran tests on Meter Registry for cache hits, misses, size.
> ENG-5066: GuavaCacheMetric Support

- .github/workflows/pr-test.yml
- platform-service-framework/build.gradle.kts
Codecov bash uploader is being deprecated and is currently in the brownout phase. We need to upgrade to the v2 gh action in all repos.
More info: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
> chore: update codecov gha to v2

- integrationtest-service-framework/src/main/java/org/hypertrace/core/serviceframework/config/IntegrationTestConfigClient.java
- integrationtest-service-framework/src/main/java/org/hypertrace/core/serviceframework/config/IntegrationTestConfigClientFactory.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/ConsolidatedGrpcServiceContainerEnvironment.java
- platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/config/ConfigClientFactory.java
The new grpc service factory container classes don't rely on environment variables for things like cluster (which were unused, and thus call the direct getConfig(x,y,z) method. This was unsupported for integration tests, so refactored to support both the prior and new styles.
Verified integration tests both in old service that hasn't been changed for backwards compat, and new service using the new grpc service factory style.
> Int test fixes

- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/ConsolidatedGrpcPlatformServiceContainer.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServerDefinition.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/PlatformPeriodicTaskDefinition.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/StandAloneGrpcPlatformServiceContainer.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/StandAloneGrpcServiceContainerEnvironment.java
This PR adds support for more common patterns shared amongst our grpc services - scheduling periodic tasks (generally health checks) tied to the server lifecycle, and splitting services to different servers/ports. All changes are backwards compatible.
> feat: add support for multiple grpc servers, scheduled tasks

- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/ConsolidatedGrpcPlatformServiceContainer.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServerDefinition.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/StandAloneGrpcPlatformServiceContainer.java
Support declaring max inbound for server
> Max inbound

- platform-http-service-framework/build.gradle.kts
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/HttpContainer.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/HttpContainerEnvironment.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/HttpHandlerDefinition.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/HttpHandlerFactory.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/ServerBuilder.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/StandAloneHttpContainerEnvironment.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/StandAloneHttpPlatformServiceContainer.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/guice/SimpleGuiceServletContextListener.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/jetty/JettyHttpContainer.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/jetty/JettyHttpServerBuilder.java
- settings.gradle.kts
Similar to previously added grpc framework, a small wrapper around existing code to allow composing one or more services, and generally make server building simpler.
Ran integration tests with a service running on this implementation
Example service using new framework: https://github.com/hypertrace/hypertrace-core-graphql/pull/105
> feat: add http service framework

- platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/PlatformService.java
Previously, if a server hit an unrecoverable error (e.g. port already bound) it would log the error and sit in purgatory, the JVM never exiting. Now, we'll clean up the server as best we can and exit.
> refactor: exit process if server fails to start

- platform-grpc-service-framework/build.gradle.kts
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformService.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-http-service-framework/build.gradle.kts
Allowing using a service definition in addition to a bindable service when declaring a service. This allows wrapping service-local interceptors (https://github.com/hypertrace/service-framework/pull/58 added support for server-wide interceptors).
> refactor: allow building service using definition

- platform-metrics/build.gradle.kts
- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
- platform-service-framework/build.gradle.kts
Support for log4j metrics
Local Testing. 
NA.
> log4j metrics

- platform-grpc-service-framework/build.gradle.kts
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/ConsolidatedGrpcPlatformServiceContainer.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-http-service-framework/build.gradle.kts
- platform-metrics/src/main/java/org/hypertrace/core/serviceframework/metrics/PlatformMetricsRegistry.java
- platform-service-framework/src/test/java/org/hypertrace/core/serviceframework/PlatformServiceTest.java
Added grpc server/client metrics monitoring.
Tested manually
NA
> grpc metrics and minor refactoring

- platform-grpc-service-framework/build.gradle.kts
- platform-http-service-framework/build.gradle.kts
- platform-metrics/build.gradle.kts
- platform-service-framework/build.gradle.kts
Update dependencies to latest to keep ahead!
> chore: update dependency versions to clear up vulnerabilities

- platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/PlatformService.java
Currently if the server dies due to an uncaught exception, it's logged and the process goes on. Updating so uncaught exceptions cause process to quit.
> fix: shutdown on uncaught exception

- platform-grpc-service-framework/build.gradle.kts
- platform-http-service-framework/build.gradle.kts
This PR updates grpc as there is a new vulnerability reported on the older version being used - `CVE-2023-33953`
> chore: upgrade grpc due to vuln

- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/HttpContainerEnvironment.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/StandAloneHttpContainerEnvironment.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/StandAloneHttpPlatformServiceContainer.java
Subclass of grpc reg should be compatible with existing usages. This enables an http and grpc server to share the same container and take advantage of in process transport.
> refactor: update http framework to provide inprocess grpc reg

- owasp-suppressions.xml
> ci: add suppression for bad cpe declaration

- owasp-suppressions.xml
- platform-http-service-framework/build.gradle.kts
- platform-metrics/build.gradle.kts
- platform-service-framework/build.gradle.kts
Upgraded version for org.eclipse.jetty:jetty-servlet from 9.4.52.v20230823 to 9.4.53.v20231009 to resolve vulnerability CVE-2023-36478
> upgraded version for org.eclipse.jetty:jetty-servlet

- docstore-metrics/build.gradle.kts
- owasp-suppressions.xml
- platform-grpc-service-framework/build.gradle.kts
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServerDefinition.java
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-http-service-framework/build.gradle.kts
- platform-service-framework/build.gradle.kts
Ref: https://github.com/hypertrace/java-grpc-utils/pull/53 (also waiting on that to resolve version refs)
> chore: update grpc, jackson

- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
Exposing histogram bucket metrics for grpc latencies instead of percentile metrics to use in SLI dashboards
The buckets are generated based on a set max value (read from application.conf). The default max is set to 10000ms which generates 8 default buckets: [+Inf, 10000, 3330, 1110, 370, 120, 40, 10] (in ms)
> Expose grpc latency histogram metrics

- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-http-service-framework/src/main/java/org/hypertrace/core/serviceframework/http/StandAloneHttpPlatformServiceContainer.java
Couple existing issues here:
- clients were being shutdown before the server, meaning we were unable to drain pending requests at the moment of shutdown
- if the service fails to start, the shutdown hook was throwing a NPE because not all variables had values yet. No functional impact here, but commonly caused log confusion.
> fix: make shutdown more graceful

- owasp-suppressions.xml
- platform-grpc-service-framework/build.gradle.kts
- platform-grpc-service-framework/src/main/java/org/hypertrace/core/serviceframework/grpc/GrpcPlatformServiceContainer.java
- platform-http-service-framework/build.gradle.kts
This new interceptor verifies that clients are adding timeouts. It is lenient and logs a warning but does not block a request if missing a timeout.
> refactor: add interceptor to verify clients are setting timeouts

- .github/workflows/build-and-test.yml
- build.gradle.kts
- owasp-suppressions.xml
- platform-metrics/build.gradle.kts
> ENG-58332:Upgrade Micrometer version
